import Head from 'next/head'
import Blogs from '@/components/Blogs'
import Hero from '@/components/Hero'
import Features from '@/components/Features'
import Team from '@/components/Team'
import Pricing from '@/components/Pricing'
import Contact from '@/components/Contact'

export default function Home() {

  return (
    <>
      <Head>
        <title>CodeLek Technology - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white dark:bg-gray-900'>
        <div className="hero">
          <Hero />
        </div>

        <div className="features">
          <Features />
        </div>

        <div className="team">
          <Team />
        </div>

        <div className="pricing">
          <Pricing />
        </div>

        <div className="blogs">
          <Blogs />
        </div>

        <div className="contact">
          <Contact />
        </div>
      </main>
    </>
  )
}
